## Introduction
I am creating a 2 layered neural network with 1 hidden layer. 
The aim is to implement the theoretically learnt concepts and get a feel of the how the algorithm generally works.


In [48]:
#importing dependencies
import numpy as np

In [76]:
# Non Linear Activation Function
def nonlin(x,deriv=False):
    if deriv:
        #Taking the derivative of the sigmoid function
        return x*(1-x)
    else:
        return 1/1+np.exp(-x)

In [50]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [51]:
#Creating Response Variables 
y = np.array([[0,0,1,1]]).T
y

array([[0],
       [0],
       [1],
       [1]])

In [52]:
#Setting the seeds for recreating the results
np.random.seed(1)

In [66]:
#Initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
syn0

array([[-0.1653904 ],
       [ 0.11737966],
       [-0.71922612]])

In [78]:
#Creating Iterations for Forward propogation, Calculating error
for iter in range(10000):
    
    #Forward Propogation
    l0 = X            #Layer 0 - Input
    l1 = nonlin(np.dot(l0,syn0))       #Layer 1 - passing through activation function
#     print(l1)
    #l1 is the output of the activation function, and also the result in our case as it is just a 2-layered neural network with just one hidden layer in between
    
    #Calculating the Error -> By how much did we miss?
    l1_error = y - l1
    
    #Multiplying how much we missed by the Sigmoid slope
    l1_delta = l1_error * nonlin(l1,True)
    
    
    # Updating Weights 
    syn0 += np.dot(l0.T,l1_delta)
    
print( "Output After Training")
print(l1)

    
    

Output After Training
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]


## Thus the simple neural network was able to predict the actual y-values by adjusting the weights

# More on this later
